### ISSUE TITLE
Set Comment When Generating SSH Keys

### ISSUE THREAD

**Issue by tryton-vanmeer** [nickthecook/ops#61]
Ops should override the comment for the SSH keys it creates.

https://github.com/nickthecook/ops/blob/00ff6248307ea47342b2afe39fdaeeed0342cc0b/lib/dependencies/sshkey.rb#L38-L39

When running `ssh-keygen`, the option `-C` would be used.

https://github.com/nickthecook/ops/blob/00ff6248307ea47342b2afe39fdaeeed0342cc0b/lib/dependencies/sshkey.rb#L58-L59

Ops already has a comment it passes to ssh-add that shows up when running `ssh-add -l`. This could be passed to `ssh-keygen` as well. The comment could also be updated to be in the form `Ops.project_name@ops`.

**Comment by nickthecook** [comment]
The key comment would, in theory, be the same in both the agent key list and the public key file.

However, I find when listing keys in the agent I actually want to know what project they key is from. This is because with the typical comment format `user@host` all SSH keys I generate have the same comment.

I'm inclined to leave the agent comment as is and add an option to let the user set the comment stored in the public key file. That way, listing keys in the agent would show what projects I've got the keys for, and the file would show who created the key in GitLab.

Thoughts?

**Comment by tryton-vanmeer** [comment]
Makes sense to include a separate config option for the sshkey comment. 

When that isn't configured, ops could always fallback to using the same `key_comment` it uses for the agent, or do as it's doing and let ssh-keygen handle it.

I like making it obvious this key was generated by ops, since the comment is mostly arbitrary.

Does it matter to show who created the key, if it's generated by ops and commited in a repo?

**Comment by nickthecook** [comment]
Maybe not the specific person in a corporate dev team setup. You might want to configure, e.g., `team_name@company` for all your keys.

The use case for having an identity like this in the file is more about auditing keys on a deployed VM than looking at source code. The public key with the comment `team_name@company` would identify your key on a VM for you, compared to `partner@other_company` or something like that.

**Comment by nickthecook** [comment]
1.4.0.rc1 uses adds `options.sshkey.key_file_comment`, and uses `user@host` by default, where `host` is the output of `hostname -s` so we don't get random home network names in there.

You can try it with `gem i --pre ops_team`.

**Comment by nickthecook** [comment]
This has been in the last few released versions.

I did not change the comment when adding the key to the agent: that should remain `#{project_name}` for reasons described above.

The comment that goes in the file is configurable.
