### ISSUE TITLE
sshkey: Update Security Settings

### ISSUE THREAD

**Issue by tryton-vanmeer** [nickthecook/ops#63]
`ops` currently uses RSA with a key size of 2048. For best security, that key size should be increased to 3072 or 4096.

Even better, the algorithm could be switched to Ed25519.

Ed25519 requires a minimum of OpenSSH 6.5 (January 2014), and all supported OSs provide a newer version.

Some more info on Ed25519 https://ed25519.cr.yp.to/index.html

**Comment by nickthecook** [comment]
Fixed in v1.7.0. [Docs](https://github.com/nickthecook/ops/blob/main/docs/dependencies.md#sshkey) are updated.

Changes in this release:

- default `key_size` is 4096
- `key_algo` can be any string that `ssh-keygen` accepts

Previously, the user could configure the key size but not the key algorithm.

Using `key_size` with an algorithm of `ed25519` won't change the key size since all ED25519 keys are 256b.
